### PR TITLE
Added support for using a custom elasticsearch configuration directory

### LINKED ISSUE #28: Support using a custom elasticsearch configuration directory
_From @mmaslowskicc on June 17, 2015 12:38_

```
        command_exec = '''
            {deamon} -p {pidfile} --http.port={port}
            --path.home={home_path}  --default.path.logs={logs_path}
            --default.path.work={work_path}
            --default.path.conf=/etc/elasticsearch
[...]
```

So configuration is taken from the system-wide `/etc/elasticsearch` directory. This prevents packages using pytest-dbfixtures from using custom configuration included in their repositories, maintained via pull requests and used on CI where the test suite has no permission to write in `/etc`. (It can be useful to customize e.g. log verbosity for tests.)

_Copied from original issue: ClearcodeHQ/pytest-dbfixtures#122_

### PR DESCRIPTION
**Pull request by yashmehrotra**
Fixes #28 .

Added `conf_path` as an option

### CODE REVIEW

**Comment by yashmehrotra** [comment]
Can anyone tell me why the tests are failing, since i'm using the previous path as a default

**Comment by fizyk** [comment]
I haven't got around to fix it. Problem is with actually starting elasticsearch >= 2, and test fail on travis since recent travis infrastructure update. still haven't got aound to fix these issues. That would be #60 and #27

**Comment by yashmehrotra** [comment]
@fizyk Oh. Ok. So I guess, apart from that, is everything ok in the PR ?
Any changes you'd like to suggest ?

**Comment by yashmehrotra** [comment]
Closing this because of #89

**Pull request closed without merging**
