### PR TITLE
Allow customize elasticsearch fixture scope

### PR DESCRIPTION
**Pull request by messense**
I want to create session scope elasticsearch fixture but the current code does not allow that.

### CODE REVIEW

**Comment by fizyk** [comment]
Could you sheld a bit of light on your usecase?

Askin, sicne from the experience you don't want to do that.

having this fixture as a session one would mean that you'd either have to clean the elasticsearch yourself between tests, or the elasticsearch will stay in the dirty stage between tests, and you'll end up with tests influencing other tests.
Even if you'd adjust tests to work with that, you'd have to correct them every new test. And then there's the possibility to run with xdist, and tests being randomly selected for each worker.

**Comment by messense** [comment]
You're right.

**Comment by iamthen0ise** [comment]
Hi!

Could I kindly ask to reopen the issue?

Yep, it's nice to have auto-flush on `function` scope if I test modifications — write, update, etc...
But testing search logic of my backend app, I have to make these steps:

- Put indexes
- Fill them with data
- Make my search calls
- Remove Data, Indexes
- Repeat steps above while testing another case

And it is really take time for pytest to do my search tests.

For me it's not a problem to keep in mind that my ES should be is dirty on search and clean on modifications. Also fixtures scopes make this difference both convient and explicit.

Thank you!

**Comment by fizyk** [comment]
@iamthen0ise is there a way in Elasticsearch to quick load that data? Like create a datadump, or create a template indexes out of which to load indexes, like template databases in postgresql?

Anyway, if you really need a module/session fixture and handle the cleanup yourself, all you'd need to do would be to add this in your conftest:

```
@pytest.fixture("session")
def elasticsearch_session(elasticsearch_proc):
    """Elasticsearch client fixture."""
    return Elasticsearch([{"host": elasticsearch_proc.host, "port": elasticsearch_proc.port}])
```

**Pull request closed without merging**
